/*let name="Marek";
console.log (name);
let age=44;
console.log (age);
let favouriteColour="purple";
console.log (favouriteColour);
console.log (name + age + favouriteColour);*/
let breakfast="Muesli";
console.log (breakfast);
let lunch="sandwich";
console.log (lunch);
let dinner="quiche";
console.log (dinner);
console.log (breakfast + lunch + dinner);
breakfast="porridge";
console.log (breakfast);
lunch="salad";
console.log (lunch);
dinner="lasagne";
console.log (dinner);
console.log ('yesterday I ate ${breakfast + lunch + dinner}');